/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "Platform_Types.h"
#include "Utils.h"

#include "stm32f103c6_GPIO_Driver.h"



void clock_init(void)
{
	RCC_GPIOA_CLK_EN();	// enable IOPA
	RCC_GPIOB_CLK_EN();	// enable IOPB
}



void wait_ms(vuint32_t time)
{
	vuint32_t i, j;

	for(i = 0; i < time; ++i)
		for(j = 0; j < 255; ++j);
}

int main(void)
{
	/* initializing modules*/
	clock_init();

	GPIO_PinConfig_t pin;
	pin.GPIO_PinMode	= GPIO_MODE_OUTPUT_GP_PP_2MHz;
	pin.GPIO_PinNumber  = GPIO_PIN_13 | GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOB, &pin);

	pin.GPIO_PinMode	= GPIO_MODE_INPUT_FLOATING;
	pin.GPIO_PinNumber  = GPIO_PIN_13 | GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOA, &pin);

	/* Loop forever */
	for(;;)
	{
		if(MCAL_GPIO_readPin(GPIOA, GPIO_PIN_1) == 0)
		{
			MCAL_GPIO_togglePin(GPIOB, GPIO_PIN_1);

			while(MCAL_GPIO_readPin(GPIOA, GPIO_PIN_1) == 0);
		}

		if(MCAL_GPIO_readPin(GPIOA, GPIO_PIN_13) == 1)
		{
			wait_ms(200);
			if(MCAL_GPIO_readPin(GPIOA, GPIO_PIN_13) == 1)
			{
				MCAL_GPIO_togglePin(GPIOB, GPIO_PIN_13);
			}
		}

		wait_ms(1);
	}
}

