/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "Platform_Types.h"
#include "Utils.h"

// clock addresses
#define RCC_BASE 		0x40021000
#define RCC_APB2ENR 	*((vuint32_t *) (RCC_BASE + 0x18))

// GPIOA adresses
#define GPIOA_BASE 		0x40010800
#define GPIOA_CRL		*((vuint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_CRH		*((vuint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_IDR		*((vuint32_t *)(GPIOA_BASE + 0x08))
#define GPIOA_ORD		*((vuint32_t *)(GPIOA_BASE + 0x0c))

// GPIOB adresses
#define GPIOB_BASE 		0x40010C00
#define GPIOB_CRL		*((vuint32_t *)(GPIOB_BASE + 0x00))
#define GPIOB_CRH		*((vuint32_t *)(GPIOB_BASE + 0x04))
#define GPIOB_IDR		*((vuint32_t *)(GPIOB_BASE + 0x08))
#define GPIOB_ORD		*((vuint32_t *)(GPIOB_BASE + 0x0c))

void clock_init(void)
{
	SET_BIT(RCC_APB2ENR, 2);	// enable IOPA
	SET_BIT(RCC_APB2ENR, 3);	// enable IOPB
}

void GPIO_init(void)
{
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;

	/* Port A pin 1 and 13 as floating input mode */
	SET_BIT(GPIOA_CRL, 6);
	SET_BIT(GPIOA_CRH, 22);

	/* configure port B pin 1 and 13 to be push-pull output at 10MHz */
	GPIOB_CRL &= 0xffffff0f;
	GPIOB_CRL |= 0x00000010;

	GPIOB_CRH &= 0xff0fffff;
	GPIOB_CRH |= 0x00100000;
}

void wait_ms(vuint32_t time)
{
	vuint32_t i, j;

	for(i = 0; i < time; ++i)
		for(j = 0; j < 255; ++j);
}

int main(void)
{
	/* initializing modules*/
	clock_init();
	GPIO_init();

	/* Loop forever */
	for(;;)
	{
		if(READ_BIT(GPIOA_IDR, 1) == 0)
		{
			TOGGLE_BIT(GPIOB_ORD, 1);

			while(READ_BIT(GPIOA_IDR, 1) == 0);
		}

		if(READ_BIT(GPIOA_IDR, 13) == 1)
		{
			wait_ms(200);
			if(READ_BIT(GPIOA_IDR, 13) == 1)
			{
				TOGGLE_BIT(GPIOB_ORD, 13);
			}
		}

		wait_ms(1);
	}
}

