/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_GPIO_Driver.h"
#include "stm32f103c6_EXTI_Driver.h"

#include "LCD.h"

void wait_ms(vuint32_t time)
{
	vuint32_t i, j;

	for(i = 0; i < time; ++i)
		for(j = 0; j < 255; ++j);
}

void clock_init(void)
{
	RCC_AFIO_CLK_EN();	// enable AFIO
	RCC_GPIOA_CLK_EN();	// enable IOPA
	RCC_GPIOB_CLK_EN();	// enable IOPB
}

uint8_t flag = 0;

int main(void)
{
	clock_init();

	LCD_controlConfig_t lcd;
	lcd.LCD_controlPort			= LCD_CTRL_PORT_A;
	lcd.LCD_RS_pin				= LCD_CTRL_PIN_8;
	lcd.LCD_RW_pin				= LCD_CTRL_PIN_9;
	lcd.LCD_EN_pin				= LCD_CTRL_PIN_10;

	HAL_LCD_Init(&lcd);

	EXTI_Config_t exti9;
	exti9.EXTI_PortNumber  = EXTI_PORT_B;
	exti9.EXTI_LineNumber  = EXTI_LINE_9;
	exti9.EXTI_TriggerType = EXTI_TRIGGER_RISING;
	exti9.EXTI_Enable	   = EXTI_ENABLE;

	MCAL_EXTI_Init(&exti9);


	/* Loop forever */
	while(1)
	{
		if(flag == 1)
		{
			HAL_LCD_Clear(&lcd);

			HAL_LCD_GoXY(&lcd, 0, 0);
			HAL_LCD_writeString(&lcd, (uint8_t*)"IRQ EXTI9 is");

			HAL_LCD_GoXY(&lcd, 0, 1);
			HAL_LCD_writeString(&lcd, (uint8_t*)"happened _|-");

			flag = 0;
		}
	}
}


void MCAL_EXTI9_CallBack(void)
{
	flag = 1;
}
